### ISSUE TITLE
plugin.yml not found in version v0.5.0-beta.1 while running spigot v1.21

### ISSUE THREAD

**Issue by ArifulH8** [MC-Machinations/PaperTweaks#91]
### Expected behavior

Running the server the plugin should load.

### Observed/Actual behavior

A plugin.yml file not being found is causing the server to not load the papertweaks plugin

### Steps/models to reproduce

1. Use version CraftBukkit version 4272-Spigot-34bd42b-76f59e3 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT) of spigot
2. Download PaperTweaks version v0.5.0-beta.1
3. Run Server
4. Notice in logs the plugin is not running due to error

### Plugin and Datapack List

PluginPortal, floodgate, Geyser-Spigot

### Server Version Info

[11:43:31] [Server thread/INFO]: This server is running CraftBukkit version 4272-Spigot-34bd42b-76f59e3 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
[11:43:31] [Server thread/INFO]: Checking version, please wait...
[11:43:31] [Thread-16/INFO]: You are running the latest version

### Plugin Version

NA as the plugin is not running 

### Other

Relevant log:

[11:36:50] [Server thread/ERROR]: Could not load 'plugins/PaperTweaks.jar'                                                                                                                                       org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml                                                                                                                                                        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]                                                                                at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]                                                                                        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]                                                                                        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:464) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]                                                                    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]                                                                       at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]                                                                                at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]                                                                     at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]                                                                                                                                                Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml                                                                                                                                                ... 8 more  

If you need anything else let me know

**Comment by Machine-Maker** [comment]
This plugin doesn't support spigot anymore. It hasn't for a couple versions.

**Comment by ArifulH8** [comment]
Thanks for the reply. Ah I was waiting for paper 1.21 so wanted to try it on spigot.
